name: Build & Deploy

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
      with:
        version: 11.x
    - name: Install dependencies
      run: |
        npm install
    - name: Build page
      run: bash build.sh
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
      with: 
        publish_dir: ./dist
        publish_branch: gh-pages
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        cname: monitor.cityofzion.io
